# Generated by Django 6.0.1 on 2026-02-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='alternate_mobile',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='landmark',
        ),
    ]
