# Generated by Django 6.0.1 on 2026-02-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0009_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
