# Generated by Django 6.0.1 on 2026-02-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0010_giftcard_created_at_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='sliders/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
