# Generated by Django 6.0.1 on 2026-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0011_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainSlider',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Order Placed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
