# Generated by Django 6.0.1 on 2026-02-08 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0015_alter_category_options_remove_order_transaction_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCard',
        ),
    ]
